name: Security Policy Enforcement

on:
# pull rquest 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  enforce-policies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Run policy enforcer
        run: |
          python3 scripts/policy_enforcer.py || (echo "Policy violation" && exit 1)
      - name: Upload policy report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: policy-report
          path: .policy_report.json
